"""
Common timeout values for external tools and operations
"""

# Tool-specific timeouts (in seconds)
DEFAULT_TIMEOUT_QUICK = 5
DEFAULT_TIMEOUT_SHORT = 10
DEFAULT_TIMEOUT_MEDIUM = 30
DEFAULT_TIMEOUT_LONG = 60
DEFAULT_TIMEOUT_VERY_LONG = 300

# Tool-specific timeouts
TIMEOUT_NMAP = DEFAULT_TIMEOUT_LONG
TIMEOUT_SUBFINDER = DEFAULT_TIMEOUT_VERY_LONG
TIMEOUT_ASSETFINDER = DEFAULT_TIMEOUT_MEDIUM
TIMEOUT_NUCLEI_SCAN = DEFAULT_TIMEOUT_LONG
TIMEOUT_NUCLEI_UPDATE = DEFAULT_TIMEOUT_VERY_LONG
TIMEOUT_CERT_CHECK = DEFAULT_TIMEOUT_SHORT
TIMEOUT_DNS = DEFAULT_TIMEOUT_SHORT
TIMEOUT_HTTP_REQUEST = DEFAULT_TIMEOUT_SHORT
